/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUpdatesIndexRouteImport } from './routes/_layout/updates/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as DeviceIdFotaInformationIndexRouteImport } from './routes/$deviceId/fota-information/index'
import { Route as DevicesIdInfoIndexRouteImport } from './routes/devices/$id/info/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUpdatesIndexRoute = LayoutUpdatesIndexRouteImport.update({
  id: '/updates/',
  path: '/updates/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const DeviceIdFotaInformationIndexRoute =
  DeviceIdFotaInformationIndexRouteImport.update({
    id: '/$deviceId/fota-information/',
    path: '/$deviceId/fota-information/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DevicesIdInfoIndexRoute = DevicesIdInfoIndexRouteImport.update({
  id: '/devices/$id/info/',
  path: '/devices/$id/info/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$deviceId/fota-information/': typeof DeviceIdFotaInformationIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/settings/': typeof LayoutSettingsIndexRoute
  '/updates/': typeof LayoutUpdatesIndexRoute
  '/devices/$id/info/': typeof DevicesIdInfoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$deviceId/fota-information': typeof DeviceIdFotaInformationIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/updates': typeof LayoutUpdatesIndexRoute
  '/devices/$id/info': typeof DevicesIdInfoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/$deviceId/fota-information/': typeof DeviceIdFotaInformationIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/updates/': typeof LayoutUpdatesIndexRoute
  '/devices/$id/info/': typeof DevicesIdInfoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$deviceId/fota-information/'
    | '/dashboard/'
    | '/settings/'
    | '/updates/'
    | '/devices/$id/info/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$deviceId/fota-information'
    | '/dashboard'
    | '/settings'
    | '/updates'
    | '/devices/$id/info'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/$deviceId/fota-information/'
    | '/_layout/dashboard/'
    | '/_layout/settings/'
    | '/_layout/updates/'
    | '/devices/$id/info/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  DeviceIdFotaInformationIndexRoute: typeof DeviceIdFotaInformationIndexRoute
  DevicesIdInfoIndexRoute: typeof DevicesIdInfoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/updates/': {
      id: '/_layout/updates/'
      path: '/updates'
      fullPath: '/updates/'
      preLoaderRoute: typeof LayoutUpdatesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/$deviceId/fota-information/': {
      id: '/$deviceId/fota-information/'
      path: '/$deviceId/fota-information'
      fullPath: '/$deviceId/fota-information/'
      preLoaderRoute: typeof DeviceIdFotaInformationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$id/info/': {
      id: '/devices/$id/info/'
      path: '/devices/$id/info'
      fullPath: '/devices/$id/info/'
      preLoaderRoute: typeof DevicesIdInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutUpdatesIndexRoute: typeof LayoutUpdatesIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutUpdatesIndexRoute: LayoutUpdatesIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  DeviceIdFotaInformationIndexRoute: DeviceIdFotaInformationIndexRoute,
  DevicesIdInfoIndexRoute: DevicesIdInfoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
